bugfix no auth jira lookup

diff --git a/bin/jira-descriptions b/bin/jira-descriptions
--- a/bin/jira-descriptions
+++ b/bin/jira-descriptions
@@ -24,12 +24,13 @@ JIRA_API_URL="${JIRA_BASE_URL}/rest/api/2"
 JIRA_DESCRIPTION_KEY="${JIRA_ISSUE_KEY:-summary}"
 
 if [ -z "${JIRA_BASE_URL:-}" ] ||
-   ! ( [ "${JIRA_NOAUTH}" = false ] || ([ -n "${JIRA_USER:-}" ] &&
+   ! ( [ "${JIRA_NOAUTH}" = true ] || ([ -n "${JIRA_USER:-}" ] &&
    [ -n "${JIRA_PASS:-}" ]; ); ); then
   echo 'ERROR: all three variables must be set.' >&2
   echo '  - JIRA_BASE_URL' >&2
   echo '  - JIRA_USER' >&2
   echo '  - JIRA_PASS' >&2
+  echo 'Set JIRA_NOAUTH=true to skip user and pass variables.' >&2
   exit 1
 fi
 
@@ -56,6 +57,11 @@ function checkutil() (
 
 checkutil jq
 checkutil curl
+
+if [ "$#" -le 0 ]; then
+  echo 'ERROR: Provide one or more JIRA tickets as arguments.' >&2
+  exit 1
+fi
 
 TMP_DIR="$(mktemp -d)"
 trap 'rm -rf "${TMP_DIR}"' EXIT
